message: test
server:
  port: 12581
spring:
  application:
    name: Config_Client
  cloud:
    config:
      profile: dev
      label: master
      uri: http://root:123@127.0.0.1:12580
      username: root
      password: 123
      discovery:
        enabled: true
        service-id: Config_Server
  rabbitmq:
    host: 106.52.151.187
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123@106.52.151.187:8080/eureka/


